### ISSUE TITLE
Does the oauth proxy allow for public_content scope?

### ISSUE THREAD

**Issue by mercadonicolas** [polevaultweb/instagrate-to-wordpress#2]
Hi. Thanks for this plugin!

I'm trying to implement it on a site but my requirements are a bit different. I still need to create posts, etc, but I want to do it base on media coming from a hashtag search.
I'm trying to hit `https://graph.instagram.com/ig_hashtag_search?access_token=IGQVJVRHZANRmowUmF0cTM2ZAVcxNTlnYk1rcVhZAREctUTZAhSjlvSFk2bWt1akpVUUtFaTEtX1czQmZApcHhVZAktsa3lHQVJhajNuVERnTDd5WWZAzRlg2SjVORjFPYXZAvaUhoYlJ3R1NB&user_id=17915980127366114&q=fashion` but then I get:
```
{
   "error": {
      "message": "Unsupported get request. Object with ID 'ig_hashtag_search' does not exist, cannot be loaded due to missing permissions, or does not support this operation",
      "type": "IGApiException",
      "code": 100,
      "error_subcode": 33,
      "fbtrace_id": "ApAws-DAlmlIU3tfC_ALaKs"
   }
}
```
I would expect this endpoint to work. Could it be that the proxy at `l.instagrate.io` does not support the `public_content` scope?
Anyway, if you per chance have any ideas on why the hashtag search might not be working, I'd be very grateful.
Once I get this working, I can submit a PR if you want to merge the hashtag option in.

**Comment by polevaultweb** [comment]
This endpoint was always a pro-only feature, but was later removed from the Instagram API.
